# Importing Data Using Pandas - Lab

## Introduction

In this lab, you'll get some practice with loading files with summary or metadata, and if you find that easy, the optional "level up" content covers loading data from a corrupted csv file!

## Objectives
You will be able to:

- Use pandas to import data from a CSV and and an Excel spreadsheet  

##  Loading Files with Summary or Meta Data

Load either of the files `'Zipcode_Demos.csv'` or `'Zipcode_Demos.xlsx'`. What's going on with this dataset? Clean it up into a useable format and describe the nuances of how the data is currently formatted.

All data files are stored in a folder titled `'Data'`.

In [2]:
# Import pandas using the standard alias
import pandas as pd

In [8]:
# Import the file and print the first 5 rows
df = pd.read_csv('Data/Zipcode_Demos.csv')
print(df.shape)
df.head()

(57, 47)

,0,Average Statistics,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46
0,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,JURISDICTION NAME,10005.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,COUNT PARTICIPANTS,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,COUNT FEMALE,4.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,PERCENT FEMALE,0.404,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Print the last 5 rows of df
df.tail()

,0,Average Statistics,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46
52,53,10006,6,2,0.33,4,0.67,0,0,6,...,6,100,0,0,6,1,0,0,6,100
53,54,10007,1,0,0,1,1,0,0,1,...,1,100,1,1,0,0,0,0,1,100
54,55,10009,2,0,0,2,1,0,0,2,...,2,100,0,0,2,1,0,0,2,100
55,56,10010,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
56,57,10011,3,2,0.67,1,0.33,0,0,3,...,3,100,0,0,3,1,0,0,3,100

In [7]:
# What is going on with this data set? Anything unusual?
df.isna()

,0,Average Statistics,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46
0,False,True,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
3,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
5,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
6,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
7,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
8,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
9,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
10,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
11,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
12,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
13,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
14,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
15,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
16,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
17,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
18,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
19,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
20,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
21,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
22,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
23,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
24,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
25,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
26,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
27,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
28,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
29,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
30,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
31,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
32,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
33,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
34,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
35,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
36,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
37,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
38,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
39,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
40,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
41,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
42,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
43,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
44,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
45,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
46,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
47,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
48,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
49,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
50,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
51,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
52,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
53,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
54,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
55,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
56,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [29]:
# Clean up the dataset
print(len(df.index))
print(len(df.columns))
count = 0
null_count = 0
for row in range(0,len(df.index)):
    count = 0
    null_count = 0
    #print('row {}'.format(row))
    for col in df.iloc[row].isna():
        #print('\t is col {} null? {}.'.format(count,col))
        count += 1
        if col:
            null_count += 1
    print('On row {} there are {} null values out of {} cols.'.format(row, null_count, count))

57
47
On row 0 there are 45 null values out of 47 cols.
On row 1 there are 44 null values out of 47 cols.
On row 2 there are 44 null values out of 47 cols.
On row 3 there are 44 null values out of 47 cols.
On row 4 there are 44 null values out of 47 cols.
On row 5 there are 44 null values out of 47 cols.
On row 6 there are 44 null values out of 47 cols.
On row 7 there are 44 null values out of 47 cols.
On row 8 there are 44 null values out of 47 cols.
On row 9 there are 44 null values out of 47 cols.
On row 10 there are 44 null values out of 47 cols.
On row 11 there are 44 null values out of 47 cols.
On row 12 there are 44 null values out of 47 cols.
On row 13 there are 44 null values out of 47 cols.
On row 14 there are 44 null values out of 47 cols.
On row 15 there are 44 null values out of 47 cols.
On row 16 there are 44 null values out of 47 cols.
On row 17 there are 44 null values out of 47 cols.
On row 18 there are 44 null values out of 47 cols.
On row 19 there are 44 null values out of 47 cols.
On row 20 there are 44 null values out of 47 cols.
On row 21 there are 44 null values out of 47 cols.
On row 22 there are 44 null values out of 47 cols.
On row 23 there are 44 null values out of 47 cols.
On row 24 there are 44 null values out of 47 cols.
On row 25 there are 44 null values out of 47 cols.
On row 26 there are 44 null values out of 47 cols.
On row 27 there are 44 null values out of 47 cols.
On row 28 there are 44 null values out of 47 cols.
On row 29 there are 44 null values out of 47 cols.
On row 30 there are 44 null values out of 47 cols.
On row 31 there are 44 null values out of 47 cols.
On row 32 there are 44 null values out of 47 cols.
On row 33 there are 44 null values out of 47 cols.
On row 34 there are 44 null values out of 47 cols.
On row 35 there are 44 null values out of 47 cols.
On row 36 there are 44 null values out of 47 cols.
On row 37 there are 44 null values out of 47 cols.
On row 38 there are 44 null values out of 47 cols.
On row 39 there are 44 null values out of 47 cols.
On row 40 there are 44 null values out of 47 cols.
On row 41 there are 44 null values out of 47 cols.
On row 42 there are 44 null values out of 47 cols.
On row 43 there are 44 null values out of 47 cols.
On row 44 there are 44 null values out of 47 cols.
On row 45 there are 44 null values out of 47 cols.
On row 46 there are 0 null values out of 47 cols.
On row 47 there are 0 null values out of 47 cols.
On row 48 there are 0 null values out of 47 cols.
On row 49 there are 0 null values out of 47 cols.
On row 50 there are 0 null values out of 47 cols.
On row 51 there are 0 null values out of 47 cols.
On row 52 there are 0 null values out of 47 cols.
On row 53 there are 0 null values out of 47 cols.
On row 54 there are 0 null values out of 47 cols.
On row 55 there are 0 null values out of 47 cols.
On row 56 there are 0 null values out of 47 cols.

## Level Up (Optional) - Loading Corrupt CSV files

Occasionally, you encounter some really ill-formatted data. One example of this can be data that has strings containing commas in a csv file. Under the standard protocol, when this occurs, one is supposed to use quotes to differentiate between the commas denoting fields and the commas within those fields themselves. For example, we could have a table like this:  

`ReviewerID,Rating,N_reviews,Review,VenueID
123456,4,137,This restaurant was pretty good, we had a great time.,98765`

Which should be saved like this if it were a csv (to avoid confusion with the commas in the Review text):
`"ReviewerID","Rating","N_reviews","Review","VenueID"
"123456","4","137","This restaurant was pretty good, we had a great time.","98765"`

Attempt to import the corrupt file, or at least a small preview of it. It is appropriately titled `'Yelp_Reviews_corrupt.csv'`. Investigate some of the intricacies of skipping rows to then pass over this error and comment on what you think is going on.

In [42]:
# Hint: Here's a useful programming pattern to use
try:
    # Do something
    Yelp_df = pd.read_csv('Data/Yelp_Reviews_Corrupt.csv')
except Exception as e:
    # Handle your exception e
    print(e)
    
Yelp_df = pd.read_csv('Data/Yelp_Reviews_Corrupt.csv', nrows=1600)
print(len(Yelp_df))

Error tokenizing data. C error: Expected 10 fields in line 2331, saw 11

1600

In [44]:
# # Iteration 1 
for i in range(0,10000):
    try:
        df = pd.read_csv('Data/Yelp_Reviews_Corrupt.csv', nrows=i)
    except:
        print('First failure at: {}'.format(i))
        break
df1 = pd.read_csv('Data/Yelp_Reviews_Corrupt.csv', nrows=i-1)
print(len(df))
df1.head()

First failure at: 1962
1961

,Unnamed: 0,business_id,cool,date,funny,review_id,stars,text,useful,user_id
0,1,pomGBqfbxcqPv14c3XH-ZQ,0,2012-11-13,0.0,dDl8zu1vWPdKGihJrwQbpw,5.0,I love this place! My fiance And I go here atl...,0.0,msQe1u7Z_XuqjGoqhB0J5g
1,2,jtQARsP6P-LbkyjbO1qNGg,1,2014-10-23,1.0,LZp4UX5zK3e-c5ZGSeo3kA,1.0,Terrible. Dry corn bread. Rib tips were all fa...,3.0,msQe1u7Z_XuqjGoqhB0J5g
2,4,Ums3gaP2qM3W1XcA5r6SsQ,0,2014-09-05,0.0,jsDu6QEJHbwP2Blom1PLCA,5.0,Delicious healthy food. The steak is amazing. ...,0.0,msQe1u7Z_XuqjGoqhB0J5g
3,5,vgfcTvK81oD4r50NMjU2Ag,0,2011-02-25,0.0,pfavA0hr3nyqO61oupj-lA,1.0,This place sucks. The customer service is horr...,2.0,msQe1u7Z_XuqjGoqhB0J5g
4,10,yFumR3CWzpfvTH2FCthvVw,0,2016-06-15,0.0,STiFMww2z31siPY7BWNC2g,5.0,I have been an Emerald Club member for a numbe...,0.0,TlvV-xJhmh7LCwJYXkV-cg

## Summary

Congratulations, you now practiced your Pandas-importing skills!